

==== 线程通讯方式


. synchronized配合wait和notify
.. wait和notify必须配合synchronized使用
.. wait和notify只能在被synchronized包裹的同步代码块里调用 +
否则会抛出`IllegalMonitorStateException`异常
.. wait会释放锁, sleep不释放锁
.. notify只会唤醒一个等待的线程, notifyAll会唤醒所有使用该锁等待的线程
. ReentrantLock配合Condition (重入锁)
.. `await()`使线程等待, `signal()`唤醒等待线程
.. 只能在`lock()`和`unlock()`包裹的同步代码块中, 才能调用await和signal
+
[source,java]
----
include::../../maven/src/main/java/com/rh/code/lock/ReentrantLockDemo.java[lines=12..31]
----
. CountDownLatch (计数器)
.. 执行指定的计数次数后, 唤醒等待的线程
.. 构造方法需要设置唤醒等待线程所需的计数次数
.. `await()`使线程等待, `countDown()`进行一次计数
+
[source,java]
----
include::../../maven/src/main/java/com/rh/code/lock/CountDownLatchDemo.java[lines=11..25]
----
. CyclicBarrier (栅栏)
.. 进入等待的线程达到指定数量时, 唤醒所有等待的线程
.. 构造方法需要设置多少个线程等待时, 才一起唤醒
+
[source,java]
----
include::../../maven/src/main/java/com/rh/code/lock/CyclicBarrierDemo.java[lines=11..30]
----
. ReentrantReadWriteLock (读写锁)
.. 在读多写少的情况性能高于重入锁. 读锁下可以并发执行, 写锁下需要依次执行
.. 读读共享, 写写互斥, 读写互斥
+
[source,java]
----
include::../../maven/src/main/java/com/rh/code/lock/ReentrantReadWriteLockDemo.java[lines=11..23]
----
. StampedLock (JDK8新读写锁)
.. `ReentrantReadWriteLock`本身适用于读多写少的情况, 读多写少的情况就会出现写线程饥渴 +
少量的写线程和大量的读线程竞争资源, 写线程被读线程阻塞 +
.. `StampedLock`使用乐观锁只校验读取的数据是否被修改过, 读操作不再阻塞写操作 +
如果要保证读取的数据是最新的, 在读取数据和业务处理后, 校验如果数据被修改了, 需要处理重新读取和处理的逻辑
.. 通过`tryOptimisticRead()`获取乐观锁, 返回当前数据版本标记`stamp` +
如果在获取乐观锁时, 已经有其他线程获取了写锁, 就会返回`0`
.. 通过`validate(stamp)`校验当前数据是否被修改
.. 写锁
+
[source,java]
----
include::../../maven/src/main/java/com/rh/code/lock/StampedLockDemo.java[lines=11..33]
----
. Semaphore (信号量)
.. 限制同时执行的线程数
.. `acquire()`获取许可证, `release()`释放许可证
+
[source,java]
----
include::../../maven/src/main/java/com/rh/code/lock/SemaphoreDemo.java[lines=11..33]
----